# Generated by Django 2.1.5 on 2019-02-04 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esxicfg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='network_autoconfig',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='node',
            name='network_manualgw',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='node',
            name='network_manualip',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='node',
            name='network_manualnm',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='node',
            name='network_vlan',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='ssh_config',
            field=models.IntegerField(default=0),
        ),
    ]
